---
- name: Install Java 17
  hosts: localhost
  become: yes

  tasks:
    - name: Add Linux Uprising repository
      apt_repository:
        repo: ppa:linuxuprising/java
        state: present

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: latest
